export const CHANGE_SEARCH_FIELD='CHANGE_SEARCH_FIELD';

export const REQUESR_ROBOTS_PENDING = 'REQUESR_ROBOTS_PENDING';
export const REQUESR_ROBOTS_SUCCESS = 'REQUESR_ROBOTS_SUCCESS';
export const REQUESR_ROBOTS_FAILED = 'REQUESR_ROBOTS_FAILED';
